var quotes = [
  'I would not chug this Mountain Dew Throwback for a million dollars.',
  'I drank like three or four little chugs of this and my balls hurt. Right now. It has to be related.',
  'I value non-testicular pain.',
  'Hey Mr. President, uhh, can you like chug this Mountain Dew and shit your pants?',
  'When Abraham Lincoln fuckin\' created the universe this is not what he thought was gonna happen.',
  'No, I\'m not gonna turn this into like a fetish stream. I\'m not doing that.',
  'What, you\'re telling me I just can\'t slide like a DVD player into my pants and walk out? Why not?',
  'No that\'s actually true, I\'m not making that up, that\'s real. This is like the 5% time (sic) when I\'m saying something real.',
  'Welcome to Dark Souls games, if your back\'s in a corner, you may as well go microwave a fuckin\' burrito.',
  'He kicked me, Mom, he kicked me in the face from across the fucking game!',
  'Yeah, take a picture of my mouth!',
  'Hey, get ready for some fake reactions.',
  'Suck my fuckin\' bum.',
  'Maybe like 5% of you are chumps.',
  'You ever shoved a wrench up your ass?',
  'Shit in my face.',
  'And my hand is just caked with shit.',
  'Im on crack today, I\'m gonna be honest with you.',
  'Hey, shove those bone dragons up your ass, you fuckin\' dick.',
  'Pineapple on pizza is fucking disgusting.',
  'The Witcher 3 is not a good game at all. I think it should never have received even one award.',
  'Half-Life 1 and Half-Life 2, like I mean really that whole company in general just made nothing but 4/10 games.',
  'No, I\'m not going to shave my armpits. I manage my armpits.',
  'Don\'t you hate it when you have chicken bones in your coffee?',
  'Coffee, Cheetos, Chicken.',
  'Get ready for a real jock-shocker.',
  'Hey, how about you suck a fart outta my ass.',
  'Do you eat ass?',
  'Do you know what it\'s like to shit?',
  'I\'m hiding my penis because people are outta control!',
  'I sound like an attitude boy.',
  'Jell-O is somebody spitting a cold loogie down your throat.',
  'Everybody knows at Burger King there are fuckin\' ants everywhere.',
  'I can\'t call Luigi anymore, he called up Verizon and had my number fuckin\' blocked. Permanently.',
  'Am I the porn?',
  'Why can\'t we just eat shit?',
  'I\'m on drugs you motherfuckers!',
  'I would suck to be him.',
  'If you can\'t accept me at my worst, obey your thirst.',
  'It\'s over!',
  'I wake up, I look at the ceiling, I go \'Yo! Merry Christmas!\', and then I diarrhea. Every single morning.',
  'You can pee on me all you want, I don\'t care.',
  'Piss on me, piss in my face!',
  'Gonna shit in everybody is this room\'s cereal.',
  'If I don\'t get three headshots in a row right now, I\'m going to reach into the toilet and eat my own shit.',
  'I\'ll be back, I gotta go eat my own shit.',
  'Do you know what it\'s like to shit?',
  'You know don\'t say s-swears.',
  'I\'m seriously gonna go sit down on the toilet and piss up into my face.',
  'Lets put cigarettes out on my dick!',
];
